name: Temp Mail Bot Trigger

on:
  workflow_dispatch: # You can trigger it manually or set it to run on specific events

jobs:
  create_temp_email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch temporary email address
      run: |
        echo "Fetching temp email address..."
        
        # Fetch the temp email API response
        RESPONSE=$(curl -s https://api.mail.tm/accounts)
        
        # Print the raw response for debugging
        echo "API Response: $RESPONSE"

        # Try to parse the response with jq
        EMAIL=$(echo $RESPONSE | jq -r '.address')
        PASSWORD=$(echo $RESPONSE | jq -r '.password')

        # If parsing fails, provide error messages
        if [ -z "$EMAIL" ] || [ -z "$PASSWORD" ]; then
          echo "Error: Failed to parse the email or password"
          exit 1
        fi

        echo "Email: $EMAIL"
        echo "Password: $PASSWORD"

        # Save to file for later use
        echo $EMAIL > email.txt
        echo $PASSWORD > password.txt

        # Send it to Telegram (adjust as needed)
        TELEGRAM_TOKEN=<Your Telegram Bot Token>
        CHAT_ID=<Your Telegram Chat ID>

        curl -X POST "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage" \
            -d "chat_id=$CHAT_ID" \
            -d "text=Temp Mail Created:\nEmail: $EMAIL\nPassword: $PASSWORD"
