name: Temp Mail Bot Trigger

on:
  workflow_dispatch: # You can trigger it manually or set it to run on specific events

jobs:
  create_temp_email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get temporary email and password
      run: |
        echo "Fetching temp email address..."
        EMAIL=$(curl -s https://api.mail.tm/accounts)
        PASSWORD=$(echo $EMAIL | jq -r '.password')
        EMAIL_ADDRESS=$(echo $EMAIL | jq -r '.address')

        echo "Email: $EMAIL_ADDRESS"
        echo "Password: $PASSWORD"

        # Save to file
        echo $EMAIL_ADDRESS > email.txt
        echo $PASSWORD > password.txt

        # Trigger the Telegram Bot API to send this data
        TELEGRAM_TOKEN=<Your Telegram Bot Token>
        CHAT_ID=<Your Telegram Chat ID>

        curl -X POST "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage" \
            -d "chat_id=$CHAT_ID" \
            -d "text=Temp Mail Created:\nEmail: $EMAIL_ADDRESS\nPassword: $PASSWORD"

    - name: Send the email and password to Telegram
      run: |
        curl -F "chat_id=$CHAT_ID" -F "text=Temp Mail Created: $(cat email.txt) - Password: $(cat password.txt)" "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage"
